---
- hosts: localhost
  
  become: yes
  tasks:

  # Install Docker
  # --
  # 
  - name: install prerequisites
    apt:
      name:
        - apt-transport-https
        - ca-certificates 
        - curl 
        - gnupg-agent
        - software-properties-common
      update_cache: yes

  - name: add apt-key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: add docker repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable

  - name: install docker 
    apt:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
      update_cache: yes

  # Installs Docker SDK
  # --
  # 
  - name: install python package manager
    apt:
      name: python3-pip
  
  - name: install python sdk
    become_user: "{{ lookup('env','USER') }}"
    pip:
      name:
        - docker
        - docker-compose

  - name: run clickhouse container
    tags: clickhouse
    community.docker.docker_container:
      name: clickhouse-server
      image: clickhouse/clickhouse-server
      ulimits:
        - "nofile:262144:262144"
      ports:
        - "8123:8123"
        - "9000:9000"
      volumes:
        - /var/lib/clickhouse:/var/lib/clickhouse
      restart_policy: always
